# Generated by Django 6.0.4 on 2026-05-27 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested', models.CharField(verbose_name=100)),
                ('rec_1', models.CharField(verbose_name=100)),
                ('rec_2', models.CharField(verbose_name=100)),
                ('rec_3', models.CharField(verbose_name=100)),
                ('rec_4', models.CharField(verbose_name=100)),
                ('rec_5', models.CharField(verbose_name=100)),
                ('rec_6', models.CharField(verbose_name=100)),
                ('rec_7', models.CharField(verbose_name=100)),
                ('rec_8', models.CharField(verbose_name=100)),
                ('rec_9', models.CharField(verbose_name=100)),
                ('rec_10', models.CharField(verbose_name=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
