# Generated by Django 6.0.4 on 2026-05-27 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendationhistory',
            name='rating',
            field=models.CharField(default='Not Rated', verbose_name=20),
        ),
    ]
