# Generated by Django 6.0.4 on 2026-05-28 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_recommendationhistory_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionMovies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Show_ID', models.CharField(max_length=20)),
                ('Type', models.CharField(max_length=20)),
                ('Title', models.CharField(max_length=200)),
                ('Director', models.CharField(blank=True, max_length=200, null=True)),
                ('Country', models.CharField(blank=True, max_length=100, null=True)),
                ('Date_Added', models.CharField(blank=True, max_length=50, null=True)),
                ('Release_Year', models.IntegerField()),
                ('Rating', models.CharField(max_length=20)),
                ('Duration', models.CharField(blank=True, max_length=20, null=True)),
                ('Listed_In', models.CharField(max_length=300)),
            ],
        ),
    ]
